theme: jekyll-theme-hacker
lsi: false
safe: true
github:
  is_project_page: false
source: /xsj3n.github.io/
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
